name: CI-latest

on: [push]

strategy:
  matrix:
    version: [2.13.0,2.13.1,2.13.2,2.13.3,2.13.4,2.13.5]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: VERSION=${{matrix.version}} ./dev/build.sh
